# About toml, see https://github.com/BurntSushi/toml.

version = "1.0.0"

## this log config is for log file.
[log]
filepath = "/logs/2020-01-03.log"
maxsize = 100  # M
maxage = 30 # day
maxbackups = 10
compress = true

[database]
dialect = "mysql"
dsn = "root:123456@(localhost)/mall?charset=utf8&parseTime=True&loc=Local"  # <user>:<password>@(localhost)/<database>?charset=utf8&parseTime=True&loc=Local
# active = 100
# idle = 30
# idleTimeout = "30s"